name: CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup SSH Key
        shell: bash
        run: |
          echo "${{ secrets.EC2_KEY }}" > ~/project_mgmt_kp.pem
          chmod 400 ~/project_mgmt_kp.pem
      - name: Deploy Code
        shell: bash
        run: |
        # Copy all project files to the EC2 instance
          scp -o StrictHostKeyChecking=no -i ~/DjangoCDKey.pem -r ./myapp/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/Django_Project/
        
        # SSH into the EC2 instance and deploy
          ssh -o StrictHostKeyChecking=no -i ~/DjangoCDKey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd /home/${{ secrets.EC2_USER }}/Django_Project &&
            docker-compose up --build -d"

